# Generated by Django 5.2.6 on 2026-04-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='aadhaar_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='ward_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], default=1),
        ),
    ]
