# Generated by Django 5.2.6 on 2026-04-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_suggestion_aadhaar_number_suggestion_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Complete Address as per Aadhaar', null=True),
        ),
    ]
