# Generated by Django 5.2.6 on 2026-04-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('GARBAGE', 'Garbage & Solid Waste Management'), ('ROADS', 'Roads & Infrastructure'), ('DRAINAGE', 'Drainage & Waterlogging'), ('STREETLIGHTS', 'Public Streetlights'), ('WATER', 'Drinking Water Supply'), ('HEALTH', 'Public Health & Sanitation'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sub_category',
            field=models.CharField(blank=True, help_text='Specific sub-problem', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the issue', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('TERMINATED', 'Terminated')], default='PENDING', max_length=20),
        ),
    ]
