# Generated by Django 5.2.6 on 2026-04-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_complaint_category_complaint_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='address',
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo1',
            field=models.ImageField(blank=True, help_text='Photo 1 of the problem', null=True, upload_to='complaints_photos/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo2',
            field=models.ImageField(blank=True, help_text='Photo 2 of the problem', null=True, upload_to='complaints_photos/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='photo3',
            field=models.ImageField(blank=True, help_text='Photo 3 of the problem', null=True, upload_to='complaints_photos/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='video',
            field=models.FileField(blank=True, help_text='Video proof (up to 100MB)', null=True, upload_to='complaints_videos/'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='implementation_address',
            field=models.TextField(default='', help_text='Full address of the implementation area'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of this place', null=True, upload_to='suggestions_photos/'),
        ),
    ]
