# Generated by Django 5.2.6 on 2026-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_complaint_photo_remove_suggestion_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='implementation_address',
            new_name='target_address',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='ward_number',
            new_name='target_ward_number',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='suggestion_category',
            field=models.CharField(choices=[('GARBAGE', 'Garbage & Solid Waste Management'), ('ROADS', 'Roads & Infrastructure'), ('DRAINAGE', 'Drainage & Waterlogging'), ('STREETLIGHTS', 'Public Streetlights'), ('WATER', 'Drinking Water Supply'), ('HEALTH', 'Public Health & Sanitation'), ('PARKS', 'Parks & Recreation'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='ticket_number',
            field=models.CharField(db_index=True, default='TMP', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='user_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='user_ward_number',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='description',
            field=models.TextField(blank=True, help_text="User's ideas on improving the city. Mandatory if 'Other' is selected.", null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='photo',
            field=models.ImageField(default='', help_text='Photo of this place is mandatory', upload_to='suggestions_photos/'),
            preserve_default=False,
        ),
    ]
