# Generated by Django 5.2.6 on 2026-04-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_implementation_address_suggestion_target_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the target area', null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the target area', null=True),
        ),
    ]
