# Generated by Django 5.2.6 on 2026-04-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_suggestion_latitude_suggestion_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude of the problem area', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the problem area', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='target_address',
            field=models.TextField(blank=True, help_text='Full address of the problem area', null=True),
        ),
    ]
