# Generated by Django 5.2.6 on 2026-04-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_complaint_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Citizen rating 1–5 stars after complaint is resolved', null=True),
        ),
    ]
