# Generated by Django 5.2.6 on 2026-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_complaint_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Citizen satisfaction rating (1–5) after complaint is resolved', null=True),
        ),
    ]
