# Generated by Django 5.2.6 on 2026-04-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_complaint_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reopen_deadline',
            field=models.DateTimeField(blank=True, help_text='7-day deadline to re-open after resolution', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reopened_at',
            field=models.DateTimeField(blank=True, help_text='When citizen re-opened the complaint', null=True),
        ),
    ]
