# Generated by Django 5.2.6 on 2026-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_reopen_fields_to_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='complaints_photos/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='complaints_photos/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='complaints_photos/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Citizen satisfaction rating (1–5) after resolution', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reopen_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='target_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='complaints_videos/'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='aadhaar_number',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='description',
            field=models.TextField(blank=True, help_text="Mandatory when category is 'Other'", null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address as per Aadhaar', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='encrypted_aadhaar',
            field=models.CharField(blank=True, help_text='Fernet-encrypted Aadhaar number at rest', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Mobile Number for Citizens; Employee ID for Admins', max_length=50, unique=True),
        ),
    ]
