# Generated by Django 5.2.6 on 2026-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_complaint_description_alter_complaint_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of Aadhaar for duplicate detection', max_length=64, null=True, unique=True),
        ),
    ]
