# Generated by Django 5.2.6 on 2026-04-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizen_id',
            field=models.CharField(blank=True, help_text='Unique random ID like BM-XXXXXX', max_length=9, null=True, unique=True),
        ),
    ]
