# Generated by Django 5.2.6 on 2026-04-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_complaint_priority_complaint_resolution_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('GARBAGE', 'Garbage & Solid Waste Management'), ('ROADS', 'Roads & Infrastructure'), ('DRAINAGE', 'Drainage & Waterlogging'), ('STREETLIGHTS', 'Public Streetlights'), ('WATER', 'Drinking Water Supply'), ('HEALTH', 'Public Health & Sanitation'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='LOW', help_text='Issue priority set by admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('TERMINATED', 'Terminated')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ward_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], db_index=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='target_ward_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')], db_index=True, default=1),
        ),
    ]
