# Generated by Django 5.2.6 on 2026-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_complaint_category_alter_complaint_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='appeal_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='appealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_photo',
            field=models.ImageField(blank=True, help_text='Proof of resolution photo uploaded by admin', null=True, upload_to='resolutions_photos/'),
        ),
    ]
