# Generated by Django 5.2.6 on 2026-05-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_card_document',
            field=models.FileField(blank=True, help_text='Uploaded Aadhaar Card Document (JPG/JPEG only)', null=True, upload_to='aadhaar_documents/'),
        ),
    ]
